localhost:
  ip: localhost
  port: 8888
  server-name: 微信账单处理
dataBase:
  ip: ${localhost.ip}
  port: 3306
  dbname: bill-test1
  username: lzp
  password: 123456
server:
  port: ${localhost.port}
  servlet:
    application-display-name: ${localhost.server-name}
spring:
  datasource:
    url: jdbc:mysql://${dataBase.ip}:${dataBase.port}/${dataBase.dbname}?serverTimezone=GMT%2B8&useSSL=false
    username: ${dataBase.username}
    password: ${dataBase.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: ${dataBase.dbname}
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  file:
    name: /log/${my.server-name}.log
  flyway:
    baseline-on-migrate: true